# Generated by Django 3.1.2 on 2020-11-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0001_initial'),
    ]

    operations = [
    ]
