# Generated by Django 3.1.1 on 2020-12-16 00:33

from django.conf import settings
from django.db import migrations, models
import recipick.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_user',
            field=models.ManyToManyField(blank=True, related_name='rating', through='recipick.ConnectRecipeRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planner',
            name='data',
            field=models.JSONField(default=recipick.models.default_planner, null=True),
        ),
    ]
