# Generated by Django 3.1.2 on 2020-11-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag_list',
            new_name='cateogry',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
