# Generated by Django 3.1.2 on 2020-11-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(default='0'),
        ),
    ]
