# Generated by Django 3.1.1 on 2020-11-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='point',
        ),
        migrations.RemoveField(
            model_name='user',
            name='point2',
        ),
    ]
