# Generated by Django 3.1.1 on 2020-12-15 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_list',
            field=models.ManyToManyField(through='recipick.ConnectRecipeIngredient', to='recipick.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_user',
            field=models.ManyToManyField(blank=True, related_name='rating', through='recipick.ConnectRecipeRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
