# Generated by Django 3.1.2 on 2020-11-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0002_recipe_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default='media/already.png', null=True, upload_to='blog/%Y/%m/%d'),
        ),
    ]
