# Generated by Django 3.1.2 on 2020-11-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0002_auto_20201106_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='edited',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
