# Generated by Django 3.1.2 on 2020-11-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0002_auto_20201106_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
