# Generated by Django 3.1.1 on 2020-11-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0002_remove_imagemodel_description_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(default='0'),
        ),
    ]
