# Generated by Django 3.1.1 on 2020-12-12 14:04

from django.db import migrations, models
import recipick.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0002_auto_20201210_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=recipick.models.default_planner, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='planner', to='recipick.Planner'),
        ),
    ]
