# Generated by Django 3.1.1 on 2020-11-18 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0002_auto_20201118_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='liked_user',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='scrapped_user',
            field=models.ManyToManyField(blank=True, related_name='scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
