# Generated by Django 3.1.1 on 2020-11-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0002_auto_20201106_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag_list',
            field=models.JSONField(null=True),
        ),
    ]
