# Generated by Django 3.1.2 on 2020-11-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0002_auto_20201119_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cateogry',
            new_name='category',
        ),
    ]
