# Generated by Django 3.1.2 on 2020-11-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0003_auto_20201106_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='desc_index',
        ),
    ]
