# Generated by Django 3.1.2 on 2020-11-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0003_auto_20201106_1211'),
    ]

    operations = [

    ]
