# Generated by Django 3.1.2 on 2020-12-09 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0003_auto_20201209_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rating_user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ratingUser',
            field=models.ManyToManyField(blank=True, related_name='rating', through='recipick.ConnectRecipeRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
