# Generated by Django 3.1.1 on 2020-11-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0004_auto_20201119_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
