# Generated by Django 3.1.2 on 2020-11-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0004_remove_imagemodel_desc_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='description_index',
            field=models.IntegerField(default=0),
        ),
    ]
