# Generated by Django 3.1.1 on 2020-11-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0004_remove_imagemodel_desc_index'),
        ('recipick', '0004_auto_20201106_1213'),
    ]

    operations = [
    ]
