# Generated by Django 3.1.2 on 2020-12-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0004_auto_20201209_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ratingUser',
            new_name='rating_user',
        ),
    ]
