# Generated by Django 3.1.1 on 2020-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0005_auto_20201119_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activate',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
