# Generated by Django 3.1.2 on 2020-11-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0005_imagemodel_description_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_normalized',
            field=models.IntegerField(null=True),
        ),
    ]
