# Generated by Django 3.1.1 on 2020-11-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0005_merge_20201107_0242'),
        ('recipick', '0006_auto_20201107_0803'),
    ]

    operations = [
    ]
