# Generated by Django 3.1.1 on 2020-11-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipick', '0007_merge_20201107_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
